### ISSUE TITLE
Diffuse Raytracing example freezes Gnome window manager on Ubuntu 23.04 LTS with NVidia driver 535.86.05

### ISSUE THREAD

**Issue by dcerisano** [s-macke/WebGPU-Lab#1]
Just upgraded to 23.04 LTS with latest NVidia 535.86.05 drivers.
Running [WebGPU-Lab](https://s-macke.github.io/WebGPU-Lab/build/index.html) on latest chrome-dev (`google-chrome-unstable`) 
[`google-chrome-unstable --enable-unsafe-webgpu --use-vulkan=true`](https://stackoverflow.com/questions/72294876/i-enable-webgpu-in-chrome-dev-and-it-still-doesnt-work/77011277#77011277)

Entire gnome desktop freezes immediately forcing reboot ONLY when attempting to run  `Diffuse Raytracing`  example.

Sniffing the syslog after reboot, there are hundreds of these specific errors emitted while frozen:
```
2023-09-18T12:58:00.648089-04:00 regisdixit google-chrome-unstable.desktop[3967]:  - While calling [Queue].Submit([[CommandBuffer from CommandEncoder "upload"], [Invalid CommandBuffer from CommandEncoder "renderTarget"], [CommandBuffer from CommandEncoder "render"]])
[5814:1:0918/125800.847562:ERROR:gpu_device.cc(305)] GPUDevice: [Invalid BindGroup] is invalid.
2023-09-18T12:58:00.847779-04:00 regisdixit google-chrome-unstable.desktop[3967]:  - While encoding [ComputePassEncoder].SetBindGroup(0, [Invalid BindGroup], 0, ...).
[5814:1:0918/125800.847673:ERROR:gpu_device.cc(305)] GPUDevice: [Invalid CommandBuffer from CommandEncoder "renderTarget"] is invalid.
```
Example also does not work with AMD drivers under 23.04 LTS, but does not freeze the desktop.  This error comes appears when running `google-chrome-unstable` from command-line:

```
[786897:787018:0918/204320.838329:ERROR:vulkan_swap_chain.cc(443)] vkAcquireNextImageKHR() hangs.
[786897:786897:0918/204320.838819:ERROR:gpu_service_impl.cc(1089)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[786851:786851:0918/204328.991162:ERROR:gpu_process_host.cc(990)] GPU process exited unexpectedly: exit_code=8704

```

No errors reported in chrome-dev-tools console. Other examples work fine unless Diffuse Raytracing example is attempted, then nothing works until chrome is restarted.

This example was working before the LTS upgrade, but I notice that WebGPU-Lab also is being currently updated. Possibly an upstream issue. Just a heads up.

**Comment by s-macke** [comment]
Hi dcerisano,

I have exactly the same issue with my Ubuntu and Chrome Unstable and had to restart my computer several times. 

The issue was somehow introduced with 
https://github.com/s-macke/WebGPU-Lab/commit/59f1670d6c024bbd15864e92994cbeb97939656d#diff-4ee3a8ff57d5db88a6253467fc7959e596761b5978fb884f1b02d0db06a5d3cb

The commit fixed the demos for Windows.

**Comment by dcerisano** [comment]
Have you moved those changes to the [ WebGPU-Lab](https://s-macke.github.io/WebGPU-Lab/build/index.html) website yet? I pinged the [WebGPU matrix group ](https://app.element.io/#/room/#WebGPU:matrix.org) about your site - it is very cool. Possibly the changes take a while to propagate through git pages. Will try later and close this if it passes.

I use it to smoke-test the WebGPU stack for linux, which seems to be fairly stable but still being staged for release.

I notice some changes you made to the demo can affect when the next animation frame is processed. Possibly a sync issue (race) with the Vulkan swap-chain on linux, affecting both AMD and NVidia drivers somewhere in the API stack.

**Comment by s-macke** [comment]
Thanks to https://toji.dev/webgpu-best-practices/error-handling.html I have improved the error handling and stop immediately after the first error.

Also I have refactored my code for the diffuse raytracing.

Now, it works flawless under Linux.

**Comment by dcerisano** [comment]
Tested in the wild, passing.

Should probably raise a bug against WebGPU API. It should _never_ be able to crash a desktop. Possibly something in the API stack about Vulkan swap-chain management (maybe a race condition, but it is not intermittent).

The crash only occurs with NVidia Vulkan driver, not AMD's (just a temporary freeze).  A difference there is that AMD Vulkan driver is part of the Linux kernel, but NVidia's is not (yet). Another difference is that on my AMD system Wayland is default, but on NVidia X11 is default (have not been able to get Wayland running with NVidia on 23.04).

Maybe it is a bug against kernel.org? That would be interesting. Seems to be something upstream anyway.

**Comment by dcerisano** [comment]
Just noticed that Mesa Nouveau open source kernel drivers just merged Nvidia Vulkan driver, in the "experimental" branch.
Tried to update 23.04 with it but I got nervous and backed away. Maybe try again later when the dust settles.
