### ISSUE TITLE
Migrate from `GPUAdapter.requestAdapterInfo` to `info` member

### ISSUE THREAD

**Issue by ErichDonGubler** [s-macke/WebGPU-Lab#3]
This line is going to start breaking in browsers that implement [the recent removal of `GPUAdapter.requestAdapterInfo` from the WebGPU spec.](https://github.com/gpuweb/gpuweb/pull/4662)

https://github.com/s-macke/WebGPU-Lab/blob/898e92742508f25ac9ea513acecb01cf8b1855be/src/scripts/webgpu/gpu.ts#L44

The migration, as noted in that issue, is to move to the new `info` member instead.

**Comment by ErichDonGubler** [comment]
Actually, this already _does_ break on Firefox Nightly. I got pinged about it in [bug 1927409](https://bugzilla.mozilla.org/show_bug.cgi?id=1927409). 🙂

**Comment by s-macke** [comment]
thanks. I will try it in all browsers.

**Comment by s-macke** [comment]
Thank you very much. It is difficult to stay up to date when spec changes from time to time.
